// Generated by CoffeeScript 1.6.2
(function() {
  var Contacts, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Contacts = (function(_super) {
    __extends(Contacts, _super);

    function Contacts() {
      _ref = Contacts.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Contacts.prototype.model = app.Models.Contact;

    Contacts.prototype.url = "data/contacts.json";

    return Contacts;

  })(Backbone.Collection);

  this.app = (_ref1 = window.app) != null ? _ref1 : {};

  this.app.Collections.Contacts = new Contacts;

}).call(this);
