// Generated by CoffeeScript 1.6.2
(function() {
  var Contact, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Contact = (function(_super) {
    __extends(Contact, _super);

    function Contact() {
      _ref = Contact.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return Contact;

  })(Backbone.Model);

  this.app = (_ref1 = window.app) != null ? _ref1 : {};

  this.app.Models.Contact = Contact;

}).call(this);
