// Generated by CoffeeScript 1.12.7
(function() {
  var Contacts, ref,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Contacts = (function(superClass) {
    extend(Contacts, superClass);

    function Contacts() {
      return Contacts.__super__.constructor.apply(this, arguments);
    }

    Contacts.prototype.model = app.Models.Contact;

    Contacts.prototype.url = "data/contacts.json";

    return Contacts;

  })(Backbone.Collection);

  this.app = (ref = window.app) != null ? ref : {};

  this.app.Collections.Contacts = new Contacts;

}).call(this);
