// Generated by CoffeeScript 1.12.7
(function() {
  var Contact, ref,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Contact = (function(superClass) {
    extend(Contact, superClass);

    function Contact() {
      return Contact.__super__.constructor.apply(this, arguments);
    }

    return Contact;

  })(Backbone.Model);

  this.app = (ref = window.app) != null ? ref : {};

  this.app.Models.Contact = Contact;

}).call(this);
