// Generated by CoffeeScript 1.12.7
(function() {
  var AppRouter, ref,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  AppRouter = (function(superClass) {
    extend(AppRouter, superClass);

    function AppRouter() {
      return AppRouter.__super__.constructor.apply(this, arguments);
    }

    AppRouter.prototype.routes = {
      '': 'index',
      'getting-started': 'gettingStarted',
      'fixed-header-footer': 'fixedHeaderFooter',
      'transitions': 'transitions',
      'slide': 'slide',
      'slideUp': 'slideUp',
      'contacts': 'contacts',
      'contacts/:id': 'showContact',
      'created-by': 'createdBy',
      'contribute': 'contribute'
    };

    AppRouter.prototype.index = function() {
      return glide.to('#index', false);
    };

    AppRouter.prototype.gettingStarted = function() {
      return glide.to('#getting-started', false);
    };

    AppRouter.prototype.fixedHeaderFooter = function() {
      return glide.to('#fixed-header-footer', true);
    };

    AppRouter.prototype.transitions = function() {
      return glide.to('#transitions', false);
    };

    AppRouter.prototype.slide = function() {
      return glide.to('#slide', false);
    };

    AppRouter.prototype.slideUp = function() {
      return glide.to('#slideUp', true);
    };

    AppRouter.prototype.contacts = function() {
      var view;
      view = new app.Views.Contacts({
        collection: app.Collections.Contacts
      });
      view.render();
      return glide.to('#contacts');
    };

    AppRouter.prototype.showContact = function(id) {
      var model, ref, view;
      model = (ref = app.Collections.Contacts) != null ? ref.get(id) : void 0;
      view = new app.Views.ContactsShow({
        model: model
      });
      view.render();
      return glide.to('#contact-page');
    };

    AppRouter.prototype.createdBy = function() {
      return glide.to('#created-by');
    };

    AppRouter.prototype.contribute = function() {
      return glide.to('#contribute');
    };

    return AppRouter;

  })(Backbone.Router);

  this.app = (ref = window.app) != null ? ref : {};

  this.app.Routers.AppRouter = AppRouter;

}).call(this);
